version: 2

jobs:
  build:
    docker:
      - image: xtreamwayz/php:7.1

    working_directory: ~/project

    steps:
      - checkout

      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            - composer-v1-

      - run:
          name: Install dependencies
          command: |
            composer install --no-interaction --prefer-dist --optimize-autoloader --classmap-authoritative

      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - /root/.composer/cache/files

      - run:
          name: Validate composer lock file
          command: |
            composer validate --no-check-all --no-check-publish

      - run:
          name: Run PHPUnit
          command: |
            vendor/bin/phpunit --log-junit /tmp/test-results/phpunit/junit.xml

      - run:
          name: Run PHP Coding Style Analysis
          command: |
            vendor/bin/phpcs

      - run:
          name: Run PHP Static Analysis Tool
          command: |
            vendor/bin/phpstan analyse --no-progress --level=0 src

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results
